FROM  joengenduvel/jre17:latest
WORKDIR /root
COPY ./target/graduation-0.0.1-SNAPSHOT.jar /root
ENV MYSQL_USERNAME=MYSQL_USERNAME MYSQL_PASSWORD=MYSQL_PASSWORD MYSQL_DATABASE=MYSQL_DATABASE HTTP_UPLOAD_PATH=HTTP_UPLOAD_PATH
EXPOSE 8888
CMD ["java","-jar", "graduation-0.0.1-SNAPSHOT.jar"]