spring:
  application:
    name: graduation

  redis:
    host: redis-service
    port: 6379
  datasource:
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://mysql-service:3306/${MYSQL_DATABASE}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
server:
  port: 8888

segService:
  url: http://modnet-service:5000/matting
  timeout: 60
