spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    username: root
    password: root
    url: replace
    driver-class-name: com.mysql.cj.jdbc.Driver
    #Not recommended to modify
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat, wall
  application:
    name: graduation
  servlet:
    multipart:
      #Limit the maximum size of a single file upload
      max-file-size: 5MB
      # Limit the maximum size of a single request
      max-request-size: 10MB
server:
  port: 8888
logging:
  file:
    name: graduation.log


