apiVersion: apps/v1
kind: Deployment
metadata:
  name: modnet
spec:
  selector:
    matchLabels:
      app: modnet
  template:
    metadata:
      labels:
        app: modnet
    spec:
      containers:
        - name: modnet
          image: bupt2018/modnet:2.0
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          env:
            - name: "UPLOAD"
              value: "https://www.bupt.site/upload"

---

apiVersion: v1
kind: Service
metadata:
  name: modnet-service
spec:
  selector:
    app: modnet
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000