apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    name: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      name: redis-6379
  selector:
    name: redis

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
        - name: redis-6379
          image: redis:5.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"

          command:
            - "redis-server"
